public class FactorWiseLogLevel {
    public static final String DEBUG = 'DEBUG';
    public static final String INFO = 'INFO';
    public static final String WARN = 'WARN';
    public static final String ERROR = 'ERROR';

    public static final Integer DEBUG_LEVEL = 0;
    public static final Integer INFO_LEVEL = 1;
    public static final Integer WARN_LEVEL = 10;
    public static final Integer ERROR_LEVEL = 99;

    
}